name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
          autodiscover: true
        env:
          LOG_LEVEL: 'info'